#!name=Locket Gold Ultimate (Quoc Khanh Media)
#!desc=Mở khóa Locket Gold, Huy hiệu, Icon và Video 15s.
#!author=Quoc Khanh Media

[Script]
# Locket Gold Unlocker - Cấu hình chuẩn cho adminltqk28280828
Locket_Gold = type=http-response,pattern=^https?:\/\/api\.locket-labs\.com\/v1\/(user\/me|subscriptions|config),requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/adminltqk28280828/-locketgoldquockhanhmedia/main/LocketGold.js

[MITM]
hostname = %APPEND% api.locket-labs.com
